### ISSUE TITLE
Error on 'output_masks'

### ISSUE THREAD

**Issue by sigmoidx** [normanheckscher/mnist-multi-gpu#4]
Hi, I got an error on my model.

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "test.py", line 195, in <module>
    test_model = make_parallel(test_model,ngpus)
  File "/media/whitewolf/Data/Projects/Image/Classification/multi_gpu.py", line 39, in make_parallel
    x)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 606, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2834, in _collect_previous_mask
    mask = node.output_masks[tensor_index]
AttributeError: 'Node' object has no attribute 'output_masks'
```

Any helps?

**Comment by normanheckscher** [comment]
My first thought is that you're using python 3 whereas my code was written for python 2.

Secondly, it looks like you are working with Keras. Multi GPU is now baked into the native tensorflow version of Keras. There's a how-to example in the comments of the tensorflow code.
